# -*- coding: utf-8 -*-
"""Insertion-Sort(By Halil BAKAR).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uunt7gTT_CfpkHwWsOREwIhJG_Bm8gz9
"""

#Insertion-Sort Algorithm



#[7,8,3,1,4,6,2,5]

def insertion_sort(arr):
  a=0
  for j in range(1,len(arr)):#Outer Pivot Index Passes New Element After Sorting Previous Element (Observation Pivot)
    for i in range(0,j):
      #i index starts from 0 th index and scans greater values than pivot values
      #when it finds,the constructed loop immediately deletes pivot value and
      #inserts the pivot value to before the founded large element in sorted
      #part of array
      if arr[i]>arr[j]:
        a=arr[j]
        arr.pop(j)
        arr.insert(i,a)
      if arr[i]==arr[j]:
        b=arr[j]
        arr.pop(j)
        arr.insert(i,b)
  return arr


#[8(j,i),7,3,1,4,6,2,5]
#[8(i),7(j),3,1,4,6,2,5]
# arr[i]>arr[j]------->a=arr[j]---->remove arr[j]---->arr.insert(i,a)
#[7(i),8(j),3,1,4,6,2,5]----> j=j+1
#[7(i),8,3(j),1,4,6,2,5]----->i in range(j)//if arr[i]<arr[j]---->a=arr[j]---->remove(arr[j])----->arr.insert(a)
print("Enter Array to Sort ---> ")
array=eval(input())
print("Sorted array---> ",insertion_sort(array))
